// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: api/controlplane-api.proto

#include "api/controlplane-api.pb.h"
#include "api/controlplane-api.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace api {

static const char* L4BalancerApi_method_names[] = {
  "/api.L4BalancerApi/GetConfig",
  "/api.L4BalancerApi/UpdateConfig",
  "/api.L4BalancerApi/ListServices",
  "/api.L4BalancerApi/ListBackends",
  "/api.L4BalancerApi/SetBackendStatus",
  "/api.L4BalancerApi/Ping",
  "/api.L4BalancerApi/GetBlackList",
};

std::unique_ptr< L4BalancerApi::Stub> L4BalancerApi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< L4BalancerApi::Stub> stub(new L4BalancerApi::Stub(channel, options));
  return stub;
}

L4BalancerApi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_GetConfig_(L4BalancerApi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_UpdateConfig_(L4BalancerApi_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListServices_(L4BalancerApi_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_ListBackends_(L4BalancerApi_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_SetBackendStatus_(L4BalancerApi_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Ping_(L4BalancerApi_method_names[5], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBlackList_(L4BalancerApi_method_names[6], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status L4BalancerApi::Stub::GetConfig(::grpc::ClientContext* context, const ::api::GetConfigRequest& request, ::api::GetConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::GetConfigRequest, ::api::GetConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetConfig_, context, request, response);
}

void L4BalancerApi::Stub::async::GetConfig(::grpc::ClientContext* context, const ::api::GetConfigRequest* request, ::api::GetConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::GetConfigRequest, ::api::GetConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConfig_, context, request, response, std::move(f));
}

void L4BalancerApi::Stub::async::GetConfig(::grpc::ClientContext* context, const ::api::GetConfigRequest* request, ::api::GetConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::GetConfigResponse>* L4BalancerApi::Stub::PrepareAsyncGetConfigRaw(::grpc::ClientContext* context, const ::api::GetConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::GetConfigResponse, ::api::GetConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::GetConfigResponse>* L4BalancerApi::Stub::AsyncGetConfigRaw(::grpc::ClientContext* context, const ::api::GetConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status L4BalancerApi::Stub::UpdateConfig(::grpc::ClientContext* context, const ::api::UpdateConfigRequest& request, ::api::UpdateConfigResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::UpdateConfigRequest, ::api::UpdateConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_UpdateConfig_, context, request, response);
}

void L4BalancerApi::Stub::async::UpdateConfig(::grpc::ClientContext* context, const ::api::UpdateConfigRequest* request, ::api::UpdateConfigResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::UpdateConfigRequest, ::api::UpdateConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateConfig_, context, request, response, std::move(f));
}

void L4BalancerApi::Stub::async::UpdateConfig(::grpc::ClientContext* context, const ::api::UpdateConfigRequest* request, ::api::UpdateConfigResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_UpdateConfig_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::UpdateConfigResponse>* L4BalancerApi::Stub::PrepareAsyncUpdateConfigRaw(::grpc::ClientContext* context, const ::api::UpdateConfigRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::UpdateConfigResponse, ::api::UpdateConfigRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_UpdateConfig_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::UpdateConfigResponse>* L4BalancerApi::Stub::AsyncUpdateConfigRaw(::grpc::ClientContext* context, const ::api::UpdateConfigRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncUpdateConfigRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status L4BalancerApi::Stub::ListServices(::grpc::ClientContext* context, const ::api::ListServicesRequest& request, ::api::ListServicesResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::ListServicesRequest, ::api::ListServicesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListServices_, context, request, response);
}

void L4BalancerApi::Stub::async::ListServices(::grpc::ClientContext* context, const ::api::ListServicesRequest* request, ::api::ListServicesResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::ListServicesRequest, ::api::ListServicesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListServices_, context, request, response, std::move(f));
}

void L4BalancerApi::Stub::async::ListServices(::grpc::ClientContext* context, const ::api::ListServicesRequest* request, ::api::ListServicesResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListServices_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::ListServicesResponse>* L4BalancerApi::Stub::PrepareAsyncListServicesRaw(::grpc::ClientContext* context, const ::api::ListServicesRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::ListServicesResponse, ::api::ListServicesRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListServices_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::ListServicesResponse>* L4BalancerApi::Stub::AsyncListServicesRaw(::grpc::ClientContext* context, const ::api::ListServicesRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListServicesRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status L4BalancerApi::Stub::ListBackends(::grpc::ClientContext* context, const ::api::ListBackendsRequest& request, ::api::ListBackendsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::ListBackendsRequest, ::api::ListBackendsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ListBackends_, context, request, response);
}

void L4BalancerApi::Stub::async::ListBackends(::grpc::ClientContext* context, const ::api::ListBackendsRequest* request, ::api::ListBackendsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::ListBackendsRequest, ::api::ListBackendsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListBackends_, context, request, response, std::move(f));
}

void L4BalancerApi::Stub::async::ListBackends(::grpc::ClientContext* context, const ::api::ListBackendsRequest* request, ::api::ListBackendsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ListBackends_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::ListBackendsResponse>* L4BalancerApi::Stub::PrepareAsyncListBackendsRaw(::grpc::ClientContext* context, const ::api::ListBackendsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::ListBackendsResponse, ::api::ListBackendsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ListBackends_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::ListBackendsResponse>* L4BalancerApi::Stub::AsyncListBackendsRaw(::grpc::ClientContext* context, const ::api::ListBackendsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncListBackendsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status L4BalancerApi::Stub::SetBackendStatus(::grpc::ClientContext* context, const ::api::SetBackendStatusRequest& request, ::api::SetBackendStatusResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::SetBackendStatusRequest, ::api::SetBackendStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_SetBackendStatus_, context, request, response);
}

void L4BalancerApi::Stub::async::SetBackendStatus(::grpc::ClientContext* context, const ::api::SetBackendStatusRequest* request, ::api::SetBackendStatusResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::SetBackendStatusRequest, ::api::SetBackendStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetBackendStatus_, context, request, response, std::move(f));
}

void L4BalancerApi::Stub::async::SetBackendStatus(::grpc::ClientContext* context, const ::api::SetBackendStatusRequest* request, ::api::SetBackendStatusResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_SetBackendStatus_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::SetBackendStatusResponse>* L4BalancerApi::Stub::PrepareAsyncSetBackendStatusRaw(::grpc::ClientContext* context, const ::api::SetBackendStatusRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::SetBackendStatusResponse, ::api::SetBackendStatusRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_SetBackendStatus_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::SetBackendStatusResponse>* L4BalancerApi::Stub::AsyncSetBackendStatusRaw(::grpc::ClientContext* context, const ::api::SetBackendStatusRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSetBackendStatusRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status L4BalancerApi::Stub::Ping(::grpc::ClientContext* context, const ::api::EmptyMessage& request, ::api::EmptyMessage* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::EmptyMessage, ::api::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Ping_, context, request, response);
}

void L4BalancerApi::Stub::async::Ping(::grpc::ClientContext* context, const ::api::EmptyMessage* request, ::api::EmptyMessage* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::EmptyMessage, ::api::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, std::move(f));
}

void L4BalancerApi::Stub::async::Ping(::grpc::ClientContext* context, const ::api::EmptyMessage* request, ::api::EmptyMessage* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Ping_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::EmptyMessage>* L4BalancerApi::Stub::PrepareAsyncPingRaw(::grpc::ClientContext* context, const ::api::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::EmptyMessage, ::api::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Ping_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::EmptyMessage>* L4BalancerApi::Stub::AsyncPingRaw(::grpc::ClientContext* context, const ::api::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPingRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status L4BalancerApi::Stub::GetBlackList(::grpc::ClientContext* context, const ::api::EmptyMessage& request, ::api::GetBlackListResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::api::EmptyMessage, ::api::GetBlackListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBlackList_, context, request, response);
}

void L4BalancerApi::Stub::async::GetBlackList(::grpc::ClientContext* context, const ::api::EmptyMessage* request, ::api::GetBlackListResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::api::EmptyMessage, ::api::GetBlackListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlackList_, context, request, response, std::move(f));
}

void L4BalancerApi::Stub::async::GetBlackList(::grpc::ClientContext* context, const ::api::EmptyMessage* request, ::api::GetBlackListResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBlackList_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::api::GetBlackListResponse>* L4BalancerApi::Stub::PrepareAsyncGetBlackListRaw(::grpc::ClientContext* context, const ::api::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::api::GetBlackListResponse, ::api::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBlackList_, context, request);
}

::grpc::ClientAsyncResponseReader< ::api::GetBlackListResponse>* L4BalancerApi::Stub::AsyncGetBlackListRaw(::grpc::ClientContext* context, const ::api::EmptyMessage& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBlackListRaw(context, request, cq);
  result->StartCall();
  return result;
}

L4BalancerApi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      L4BalancerApi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< L4BalancerApi::Service, ::api::GetConfigRequest, ::api::GetConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](L4BalancerApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::GetConfigRequest* req,
             ::api::GetConfigResponse* resp) {
               return service->GetConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      L4BalancerApi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< L4BalancerApi::Service, ::api::UpdateConfigRequest, ::api::UpdateConfigResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](L4BalancerApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::UpdateConfigRequest* req,
             ::api::UpdateConfigResponse* resp) {
               return service->UpdateConfig(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      L4BalancerApi_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< L4BalancerApi::Service, ::api::ListServicesRequest, ::api::ListServicesResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](L4BalancerApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::ListServicesRequest* req,
             ::api::ListServicesResponse* resp) {
               return service->ListServices(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      L4BalancerApi_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< L4BalancerApi::Service, ::api::ListBackendsRequest, ::api::ListBackendsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](L4BalancerApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::ListBackendsRequest* req,
             ::api::ListBackendsResponse* resp) {
               return service->ListBackends(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      L4BalancerApi_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< L4BalancerApi::Service, ::api::SetBackendStatusRequest, ::api::SetBackendStatusResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](L4BalancerApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::SetBackendStatusRequest* req,
             ::api::SetBackendStatusResponse* resp) {
               return service->SetBackendStatus(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      L4BalancerApi_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< L4BalancerApi::Service, ::api::EmptyMessage, ::api::EmptyMessage, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](L4BalancerApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::EmptyMessage* req,
             ::api::EmptyMessage* resp) {
               return service->Ping(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      L4BalancerApi_method_names[6],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< L4BalancerApi::Service, ::api::EmptyMessage, ::api::GetBlackListResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](L4BalancerApi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::api::EmptyMessage* req,
             ::api::GetBlackListResponse* resp) {
               return service->GetBlackList(ctx, req, resp);
             }, this)));
}

L4BalancerApi::Service::~Service() {
}

::grpc::Status L4BalancerApi::Service::GetConfig(::grpc::ServerContext* context, const ::api::GetConfigRequest* request, ::api::GetConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status L4BalancerApi::Service::UpdateConfig(::grpc::ServerContext* context, const ::api::UpdateConfigRequest* request, ::api::UpdateConfigResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status L4BalancerApi::Service::ListServices(::grpc::ServerContext* context, const ::api::ListServicesRequest* request, ::api::ListServicesResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status L4BalancerApi::Service::ListBackends(::grpc::ServerContext* context, const ::api::ListBackendsRequest* request, ::api::ListBackendsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status L4BalancerApi::Service::SetBackendStatus(::grpc::ServerContext* context, const ::api::SetBackendStatusRequest* request, ::api::SetBackendStatusResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status L4BalancerApi::Service::Ping(::grpc::ServerContext* context, const ::api::EmptyMessage* request, ::api::EmptyMessage* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status L4BalancerApi::Service::GetBlackList(::grpc::ServerContext* context, const ::api::EmptyMessage* request, ::api::GetBlackListResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace api

