// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: api/controlplane-api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_api_controlplane_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{0}
}

type Backend struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Weight        uint32                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	IpVersion     uint32                 `protobuf:"varint,5,opt,name=ip_version,json=ipVersion,proto3" json:"ip_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Backend) Reset() {
	*x = Backend{}
	mi := &file_api_controlplane_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Backend) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Backend) ProtoMessage() {}

func (x *Backend) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Backend.ProtoReflect.Descriptor instead.
func (*Backend) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{1}
}

func (x *Backend) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Backend) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Backend) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *Backend) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Backend) GetIpVersion() uint32 {
	if x != nil {
		return x.IpVersion
	}
	return 0
}

type Service struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vip           string                 `protobuf:"bytes,2,opt,name=vip,proto3" json:"vip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`                     // "tcp" или "udp"
	IpVersion     uint32                 `protobuf:"varint,5,opt,name=ip_version,json=ipVersion,proto3" json:"ip_version,omitempty"` // 4 или 6
	Algorithm     string                 `protobuf:"bytes,6,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Backends      []*Backend             `protobuf:"bytes,7,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Service) Reset() {
	*x = Service{}
	mi := &file_api_controlplane_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Service) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Service) ProtoMessage() {}

func (x *Service) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Service.ProtoReflect.Descriptor instead.
func (*Service) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{2}
}

func (x *Service) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Service) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *Service) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *Service) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Service) GetIpVersion() uint32 {
	if x != nil {
		return x.IpVersion
	}
	return 0
}

func (x *Service) GetAlgorithm() string {
	if x != nil {
		return x.Algorithm
	}
	return ""
}

func (x *Service) GetBackends() []*Backend {
	if x != nil {
		return x.Backends
	}
	return nil
}

type Configuration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*Service             `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Configuration) Reset() {
	*x = Configuration{}
	mi := &file_api_controlplane_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Configuration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Configuration) ProtoMessage() {}

func (x *Configuration) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Configuration.ProtoReflect.Descriptor instead.
func (*Configuration) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{3}
}

func (x *Configuration) GetServices() []*Service {
	if x != nil {
		return x.Services
	}
	return nil
}

type GetConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Configuration         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigResponse) Reset() {
	*x = GetConfigResponse{}
	mi := &file_api_controlplane_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigResponse) ProtoMessage() {}

func (x *GetConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigResponse.ProtoReflect.Descriptor instead.
func (*GetConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetConfigResponse) GetConfig() *Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *Configuration         `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigRequest) Reset() {
	*x = UpdateConfigRequest{}
	mi := &file_api_controlplane_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigRequest) ProtoMessage() {}

func (x *UpdateConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateConfigRequest) GetConfig() *Configuration {
	if x != nil {
		return x.Config
	}
	return nil
}

type UpdateConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Errors        []string               `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"` // Ошибки валидации (если есть)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateConfigResponse) Reset() {
	*x = UpdateConfigResponse{}
	mi := &file_api_controlplane_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateConfigResponse) ProtoMessage() {}

func (x *UpdateConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateConfigResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type ServiceFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Protocol      *string                `protobuf:"bytes,1,opt,name=protocol,proto3,oneof" json:"protocol,omitempty"` // Фильтр по протоколу
	EnabledOnly   bool                   `protobuf:"varint,2,opt,name=enabled_only,json=enabledOnly,proto3" json:"enabled_only,omitempty"`
	IpVersion     *uint32                `protobuf:"varint,3,opt,name=ip_version,json=ipVersion,proto3,oneof" json:"ip_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceFilter) Reset() {
	*x = ServiceFilter{}
	mi := &file_api_controlplane_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceFilter) ProtoMessage() {}

func (x *ServiceFilter) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceFilter.ProtoReflect.Descriptor instead.
func (*ServiceFilter) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceFilter) GetProtocol() string {
	if x != nil && x.Protocol != nil {
		return *x.Protocol
	}
	return ""
}

func (x *ServiceFilter) GetEnabledOnly() bool {
	if x != nil {
		return x.EnabledOnly
	}
	return false
}

func (x *ServiceFilter) GetIpVersion() uint32 {
	if x != nil && x.IpVersion != nil {
		return *x.IpVersion
	}
	return 0
}

type ListServicesRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Filter          *ServiceFilter         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	IncludeBackends bool                   `protobuf:"varint,2,opt,name=include_backends,json=includeBackends,proto3" json:"include_backends,omitempty"`
	IncludeMetrics  bool                   `protobuf:"varint,3,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListServicesRequest) Reset() {
	*x = ListServicesRequest{}
	mi := &file_api_controlplane_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesRequest) ProtoMessage() {}

func (x *ListServicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesRequest.ProtoReflect.Descriptor instead.
func (*ListServicesRequest) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListServicesRequest) GetFilter() *ServiceFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ListServicesRequest) GetIncludeBackends() bool {
	if x != nil {
		return x.IncludeBackends
	}
	return false
}

func (x *ListServicesRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

type BackendInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	Weight        uint32                 `protobuf:"varint,3,opt,name=weight,proto3" json:"weight,omitempty"`
	Enabled       bool                   `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Metrics       *ServiceMetrics        `protobuf:"bytes,5,opt,name=metrics,proto3,oneof" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendInfo) Reset() {
	*x = BackendInfo{}
	mi := &file_api_controlplane_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendInfo) ProtoMessage() {}

func (x *BackendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendInfo.ProtoReflect.Descriptor instead.
func (*BackendInfo) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{9}
}

func (x *BackendInfo) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BackendInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *BackendInfo) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *BackendInfo) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *BackendInfo) GetMetrics() *ServiceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ServiceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Vip           string                 `protobuf:"bytes,2,opt,name=vip,proto3" json:"vip,omitempty"`
	Port          uint32                 `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Protocol      string                 `protobuf:"bytes,4,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Backends      []*BackendInfo         `protobuf:"bytes,5,rep,name=backends,proto3" json:"backends,omitempty"`
	Metrics       *ServiceMetrics        `protobuf:"bytes,6,opt,name=metrics,proto3,oneof" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceInfo) Reset() {
	*x = ServiceInfo{}
	mi := &file_api_controlplane_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceInfo) ProtoMessage() {}

func (x *ServiceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceInfo.ProtoReflect.Descriptor instead.
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{10}
}

func (x *ServiceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceInfo) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *ServiceInfo) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *ServiceInfo) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ServiceInfo) GetBackends() []*BackendInfo {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *ServiceInfo) GetMetrics() *ServiceMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type ListServicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Services      []*ServiceInfo         `protobuf:"bytes,1,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServicesResponse) Reset() {
	*x = ListServicesResponse{}
	mi := &file_api_controlplane_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServicesResponse) ProtoMessage() {}

func (x *ListServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServicesResponse.ProtoReflect.Descriptor instead.
func (*ListServicesResponse) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListServicesResponse) GetServices() []*ServiceInfo {
	if x != nil {
		return x.Services
	}
	return nil
}

type SetBackendStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Vip           string                 `protobuf:"bytes,2,opt,name=vip,proto3" json:"vip,omitempty"`
	ServicePort   uint32                 `protobuf:"varint,3,opt,name=service_port,json=servicePort,proto3" json:"service_port,omitempty"`
	BackendIp     string                 `protobuf:"bytes,4,opt,name=backend_ip,json=backendIp,proto3" json:"backend_ip,omitempty"`
	BackendPort   uint32                 `protobuf:"varint,5,opt,name=backend_port,json=backendPort,proto3" json:"backend_port,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBackendStatusRequest) Reset() {
	*x = SetBackendStatusRequest{}
	mi := &file_api_controlplane_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBackendStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBackendStatusRequest) ProtoMessage() {}

func (x *SetBackendStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBackendStatusRequest.ProtoReflect.Descriptor instead.
func (*SetBackendStatusRequest) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{12}
}

func (x *SetBackendStatusRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *SetBackendStatusRequest) GetVip() string {
	if x != nil {
		return x.Vip
	}
	return ""
}

func (x *SetBackendStatusRequest) GetServicePort() uint32 {
	if x != nil {
		return x.ServicePort
	}
	return 0
}

func (x *SetBackendStatusRequest) GetBackendIp() string {
	if x != nil {
		return x.BackendIp
	}
	return ""
}

func (x *SetBackendStatusRequest) GetBackendPort() uint32 {
	if x != nil {
		return x.BackendPort
	}
	return 0
}

func (x *SetBackendStatusRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type SetBackendStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBackendStatusResponse) Reset() {
	*x = SetBackendStatusResponse{}
	mi := &file_api_controlplane_api_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBackendStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBackendStatusResponse) ProtoMessage() {}

func (x *SetBackendStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBackendStatusResponse.ProtoReflect.Descriptor instead.
func (*SetBackendStatusResponse) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{13}
}

func (x *SetBackendStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetBackendStatusResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type ListBackendsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IncludeMetrics bool                   `protobuf:"varint,1,opt,name=include_metrics,json=includeMetrics,proto3" json:"include_metrics,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListBackendsRequest) Reset() {
	*x = ListBackendsRequest{}
	mi := &file_api_controlplane_api_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsRequest) ProtoMessage() {}

func (x *ListBackendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsRequest.ProtoReflect.Descriptor instead.
func (*ListBackendsRequest) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{14}
}

func (x *ListBackendsRequest) GetIncludeMetrics() bool {
	if x != nil {
		return x.IncludeMetrics
	}
	return false
}

type ListBackendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Backends      []*BackendInfo         `protobuf:"bytes,1,rep,name=backends,proto3" json:"backends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBackendsResponse) Reset() {
	*x = ListBackendsResponse{}
	mi := &file_api_controlplane_api_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBackendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBackendsResponse) ProtoMessage() {}

func (x *ListBackendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBackendsResponse.ProtoReflect.Descriptor instead.
func (*ListBackendsResponse) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{15}
}

func (x *ListBackendsResponse) GetBackends() []*BackendInfo {
	if x != nil {
		return x.Backends
	}
	return nil
}

type ServiceMetrics struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalPackets      uint64                 `protobuf:"varint,1,opt,name=total_packets,json=totalPackets,proto3" json:"total_packets,omitempty"`
	TcpSynPackets     uint64                 `protobuf:"varint,2,opt,name=tcp_syn_packets,json=tcpSynPackets,proto3" json:"tcp_syn_packets,omitempty"`
	PreparedPackets   uint64                 `protobuf:"varint,3,opt,name=prepared_packets,json=preparedPackets,proto3" json:"prepared_packets,omitempty"`
	ActiveConnections uint32                 `protobuf:"varint,4,opt,name=active_connections,json=activeConnections,proto3" json:"active_connections,omitempty"`
	TotalBytes        uint64                 `protobuf:"varint,5,opt,name=total_bytes,json=totalBytes,proto3" json:"total_bytes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ServiceMetrics) Reset() {
	*x = ServiceMetrics{}
	mi := &file_api_controlplane_api_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceMetrics) ProtoMessage() {}

func (x *ServiceMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceMetrics.ProtoReflect.Descriptor instead.
func (*ServiceMetrics) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{16}
}

func (x *ServiceMetrics) GetTotalPackets() uint64 {
	if x != nil {
		return x.TotalPackets
	}
	return 0
}

func (x *ServiceMetrics) GetTcpSynPackets() uint64 {
	if x != nil {
		return x.TcpSynPackets
	}
	return 0
}

func (x *ServiceMetrics) GetPreparedPackets() uint64 {
	if x != nil {
		return x.PreparedPackets
	}
	return 0
}

func (x *ServiceMetrics) GetActiveConnections() uint32 {
	if x != nil {
		return x.ActiveConnections
	}
	return 0
}

func (x *ServiceMetrics) GetTotalBytes() uint64 {
	if x != nil {
		return x.TotalBytes
	}
	return 0
}

type EmptyMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmptyMessage) Reset() {
	*x = EmptyMessage{}
	mi := &file_api_controlplane_api_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmptyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmptyMessage) ProtoMessage() {}

func (x *EmptyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_controlplane_api_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmptyMessage.ProtoReflect.Descriptor instead.
func (*EmptyMessage) Descriptor() ([]byte, []int) {
	return file_api_controlplane_api_proto_rawDescGZIP(), []int{17}
}

var File_api_controlplane_api_proto protoreflect.FileDescriptor

const file_api_controlplane_api_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/controlplane-api.proto\x12\x03api\"\x12\n" +
	"\x10GetConfigRequest\"~\n" +
	"\aBackend\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x12\x1d\n" +
	"\n" +
	"ip_version\x18\x05 \x01(\rR\tipVersion\"\xc6\x01\n" +
	"\aService\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03vip\x18\x02 \x01(\tR\x03vip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12\x1d\n" +
	"\n" +
	"ip_version\x18\x05 \x01(\rR\tipVersion\x12\x1c\n" +
	"\talgorithm\x18\x06 \x01(\tR\talgorithm\x12(\n" +
	"\bbackends\x18\a \x03(\v2\f.api.BackendR\bbackends\"9\n" +
	"\rConfiguration\x12(\n" +
	"\bservices\x18\x01 \x03(\v2\f.api.ServiceR\bservices\"?\n" +
	"\x11GetConfigResponse\x12*\n" +
	"\x06config\x18\x01 \x01(\v2\x12.api.ConfigurationR\x06config\"A\n" +
	"\x13UpdateConfigRequest\x12*\n" +
	"\x06config\x18\x01 \x01(\v2\x12.api.ConfigurationR\x06config\"H\n" +
	"\x14UpdateConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x16\n" +
	"\x06errors\x18\x02 \x03(\tR\x06errors\"\x93\x01\n" +
	"\rServiceFilter\x12\x1f\n" +
	"\bprotocol\x18\x01 \x01(\tH\x00R\bprotocol\x88\x01\x01\x12!\n" +
	"\fenabled_only\x18\x02 \x01(\bR\venabledOnly\x12\"\n" +
	"\n" +
	"ip_version\x18\x03 \x01(\rH\x01R\tipVersion\x88\x01\x01B\v\n" +
	"\t_protocolB\r\n" +
	"\v_ip_version\"\x95\x01\n" +
	"\x13ListServicesRequest\x12*\n" +
	"\x06filter\x18\x01 \x01(\v2\x12.api.ServiceFilterR\x06filter\x12)\n" +
	"\x10include_backends\x18\x02 \x01(\bR\x0fincludeBackends\x12'\n" +
	"\x0finclude_metrics\x18\x03 \x01(\bR\x0eincludeMetrics\"\xa3\x01\n" +
	"\vBackendInfo\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x03 \x01(\rR\x06weight\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabled\x122\n" +
	"\ametrics\x18\x05 \x01(\v2\x13.api.ServiceMetricsH\x00R\ametrics\x88\x01\x01B\n" +
	"\n" +
	"\b_metrics\"\xd1\x01\n" +
	"\vServiceInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03vip\x18\x02 \x01(\tR\x03vip\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x1a\n" +
	"\bprotocol\x18\x04 \x01(\tR\bprotocol\x12,\n" +
	"\bbackends\x18\x05 \x03(\v2\x10.api.BackendInfoR\bbackends\x122\n" +
	"\ametrics\x18\x06 \x01(\v2\x13.api.ServiceMetricsH\x00R\ametrics\x88\x01\x01B\n" +
	"\n" +
	"\b_metrics\"D\n" +
	"\x14ListServicesResponse\x12,\n" +
	"\bservices\x18\x01 \x03(\v2\x10.api.ServiceInfoR\bservices\"\xcb\x01\n" +
	"\x17SetBackendStatusRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x10\n" +
	"\x03vip\x18\x02 \x01(\tR\x03vip\x12!\n" +
	"\fservice_port\x18\x03 \x01(\rR\vservicePort\x12\x1d\n" +
	"\n" +
	"backend_ip\x18\x04 \x01(\tR\tbackendIp\x12!\n" +
	"\fbackend_port\x18\x05 \x01(\rR\vbackendPort\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\"Y\n" +
	"\x18SetBackendStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01B\b\n" +
	"\x06_error\">\n" +
	"\x13ListBackendsRequest\x12'\n" +
	"\x0finclude_metrics\x18\x01 \x01(\bR\x0eincludeMetrics\"D\n" +
	"\x14ListBackendsResponse\x12,\n" +
	"\bbackends\x18\x01 \x03(\v2\x10.api.BackendInfoR\bbackends\"\xd8\x01\n" +
	"\x0eServiceMetrics\x12#\n" +
	"\rtotal_packets\x18\x01 \x01(\x04R\ftotalPackets\x12&\n" +
	"\x0ftcp_syn_packets\x18\x02 \x01(\x04R\rtcpSynPackets\x12)\n" +
	"\x10prepared_packets\x18\x03 \x01(\x04R\x0fpreparedPackets\x12-\n" +
	"\x12active_connections\x18\x04 \x01(\rR\x11activeConnections\x12\x1f\n" +
	"\vtotal_bytes\x18\x05 \x01(\x04R\n" +
	"totalBytes\"\x0e\n" +
	"\fEmptyMessage2\x99\x03\n" +
	"\rL4BalancerApi\x12:\n" +
	"\tGetConfig\x12\x15.api.GetConfigRequest\x1a\x16.api.GetConfigResponse\x12C\n" +
	"\fUpdateConfig\x12\x18.api.UpdateConfigRequest\x1a\x19.api.UpdateConfigResponse\x12C\n" +
	"\fListServices\x12\x18.api.ListServicesRequest\x1a\x19.api.ListServicesResponse\x12C\n" +
	"\fListBackends\x12\x18.api.ListBackendsRequest\x1a\x19.api.ListBackendsResponse\x12O\n" +
	"\x10SetBackendStatus\x12\x1c.api.SetBackendStatusRequest\x1a\x1d.api.SetBackendStatusResponse\x12,\n" +
	"\x04Ping\x12\x11.api.EmptyMessage\x1a\x11.api.EmptyMessageB2Z0github.com/Dmitriy-M1319/l4-controlplane/api;apib\x06proto3"

var (
	file_api_controlplane_api_proto_rawDescOnce sync.Once
	file_api_controlplane_api_proto_rawDescData []byte
)

func file_api_controlplane_api_proto_rawDescGZIP() []byte {
	file_api_controlplane_api_proto_rawDescOnce.Do(func() {
		file_api_controlplane_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_controlplane_api_proto_rawDesc), len(file_api_controlplane_api_proto_rawDesc)))
	})
	return file_api_controlplane_api_proto_rawDescData
}

var file_api_controlplane_api_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_controlplane_api_proto_goTypes = []any{
	(*GetConfigRequest)(nil),         // 0: api.GetConfigRequest
	(*Backend)(nil),                  // 1: api.Backend
	(*Service)(nil),                  // 2: api.Service
	(*Configuration)(nil),            // 3: api.Configuration
	(*GetConfigResponse)(nil),        // 4: api.GetConfigResponse
	(*UpdateConfigRequest)(nil),      // 5: api.UpdateConfigRequest
	(*UpdateConfigResponse)(nil),     // 6: api.UpdateConfigResponse
	(*ServiceFilter)(nil),            // 7: api.ServiceFilter
	(*ListServicesRequest)(nil),      // 8: api.ListServicesRequest
	(*BackendInfo)(nil),              // 9: api.BackendInfo
	(*ServiceInfo)(nil),              // 10: api.ServiceInfo
	(*ListServicesResponse)(nil),     // 11: api.ListServicesResponse
	(*SetBackendStatusRequest)(nil),  // 12: api.SetBackendStatusRequest
	(*SetBackendStatusResponse)(nil), // 13: api.SetBackendStatusResponse
	(*ListBackendsRequest)(nil),      // 14: api.ListBackendsRequest
	(*ListBackendsResponse)(nil),     // 15: api.ListBackendsResponse
	(*ServiceMetrics)(nil),           // 16: api.ServiceMetrics
	(*EmptyMessage)(nil),             // 17: api.EmptyMessage
}
var file_api_controlplane_api_proto_depIdxs = []int32{
	1,  // 0: api.Service.backends:type_name -> api.Backend
	2,  // 1: api.Configuration.services:type_name -> api.Service
	3,  // 2: api.GetConfigResponse.config:type_name -> api.Configuration
	3,  // 3: api.UpdateConfigRequest.config:type_name -> api.Configuration
	7,  // 4: api.ListServicesRequest.filter:type_name -> api.ServiceFilter
	16, // 5: api.BackendInfo.metrics:type_name -> api.ServiceMetrics
	9,  // 6: api.ServiceInfo.backends:type_name -> api.BackendInfo
	16, // 7: api.ServiceInfo.metrics:type_name -> api.ServiceMetrics
	10, // 8: api.ListServicesResponse.services:type_name -> api.ServiceInfo
	9,  // 9: api.ListBackendsResponse.backends:type_name -> api.BackendInfo
	0,  // 10: api.L4BalancerApi.GetConfig:input_type -> api.GetConfigRequest
	5,  // 11: api.L4BalancerApi.UpdateConfig:input_type -> api.UpdateConfigRequest
	8,  // 12: api.L4BalancerApi.ListServices:input_type -> api.ListServicesRequest
	14, // 13: api.L4BalancerApi.ListBackends:input_type -> api.ListBackendsRequest
	12, // 14: api.L4BalancerApi.SetBackendStatus:input_type -> api.SetBackendStatusRequest
	17, // 15: api.L4BalancerApi.Ping:input_type -> api.EmptyMessage
	4,  // 16: api.L4BalancerApi.GetConfig:output_type -> api.GetConfigResponse
	6,  // 17: api.L4BalancerApi.UpdateConfig:output_type -> api.UpdateConfigResponse
	11, // 18: api.L4BalancerApi.ListServices:output_type -> api.ListServicesResponse
	15, // 19: api.L4BalancerApi.ListBackends:output_type -> api.ListBackendsResponse
	13, // 20: api.L4BalancerApi.SetBackendStatus:output_type -> api.SetBackendStatusResponse
	17, // 21: api.L4BalancerApi.Ping:output_type -> api.EmptyMessage
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_controlplane_api_proto_init() }
func file_api_controlplane_api_proto_init() {
	if File_api_controlplane_api_proto != nil {
		return
	}
	file_api_controlplane_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_api_controlplane_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_api_controlplane_api_proto_msgTypes[10].OneofWrappers = []any{}
	file_api_controlplane_api_proto_msgTypes[13].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_controlplane_api_proto_rawDesc), len(file_api_controlplane_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_controlplane_api_proto_goTypes,
		DependencyIndexes: file_api_controlplane_api_proto_depIdxs,
		MessageInfos:      file_api_controlplane_api_proto_msgTypes,
	}.Build()
	File_api_controlplane_api_proto = out.File
	file_api_controlplane_api_proto_goTypes = nil
	file_api_controlplane_api_proto_depIdxs = nil
}
