// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: api/controlplane-api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	L4BalancerApi_GetConfig_FullMethodName        = "/api.L4BalancerApi/GetConfig"
	L4BalancerApi_UpdateConfig_FullMethodName     = "/api.L4BalancerApi/UpdateConfig"
	L4BalancerApi_ListServices_FullMethodName     = "/api.L4BalancerApi/ListServices"
	L4BalancerApi_ListBackends_FullMethodName     = "/api.L4BalancerApi/ListBackends"
	L4BalancerApi_SetBackendStatus_FullMethodName = "/api.L4BalancerApi/SetBackendStatus"
	L4BalancerApi_Ping_FullMethodName             = "/api.L4BalancerApi/Ping"
)

// L4BalancerApiClient is the client API for L4BalancerApi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type L4BalancerApiClient interface {
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error)
	UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error)
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	ListBackends(ctx context.Context, in *ListBackendsRequest, opts ...grpc.CallOption) (*ListBackendsResponse, error)
	SetBackendStatus(ctx context.Context, in *SetBackendStatusRequest, opts ...grpc.CallOption) (*SetBackendStatusResponse, error)
	Ping(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error)
}

type l4BalancerApiClient struct {
	cc grpc.ClientConnInterface
}

func NewL4BalancerApiClient(cc grpc.ClientConnInterface) L4BalancerApiClient {
	return &l4BalancerApiClient{cc}
}

func (c *l4BalancerApiClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetConfigResponse)
	err := c.cc.Invoke(ctx, L4BalancerApi_GetConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l4BalancerApiClient) UpdateConfig(ctx context.Context, in *UpdateConfigRequest, opts ...grpc.CallOption) (*UpdateConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateConfigResponse)
	err := c.cc.Invoke(ctx, L4BalancerApi_UpdateConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l4BalancerApiClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, L4BalancerApi_ListServices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l4BalancerApiClient) ListBackends(ctx context.Context, in *ListBackendsRequest, opts ...grpc.CallOption) (*ListBackendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBackendsResponse)
	err := c.cc.Invoke(ctx, L4BalancerApi_ListBackends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l4BalancerApiClient) SetBackendStatus(ctx context.Context, in *SetBackendStatusRequest, opts ...grpc.CallOption) (*SetBackendStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBackendStatusResponse)
	err := c.cc.Invoke(ctx, L4BalancerApi_SetBackendStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *l4BalancerApiClient) Ping(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*EmptyMessage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmptyMessage)
	err := c.cc.Invoke(ctx, L4BalancerApi_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// L4BalancerApiServer is the server API for L4BalancerApi service.
// All implementations must embed UnimplementedL4BalancerApiServer
// for forward compatibility.
type L4BalancerApiServer interface {
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error)
	UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error)
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	ListBackends(context.Context, *ListBackendsRequest) (*ListBackendsResponse, error)
	SetBackendStatus(context.Context, *SetBackendStatusRequest) (*SetBackendStatusResponse, error)
	Ping(context.Context, *EmptyMessage) (*EmptyMessage, error)
	mustEmbedUnimplementedL4BalancerApiServer()
}

// UnimplementedL4BalancerApiServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedL4BalancerApiServer struct{}

func (UnimplementedL4BalancerApiServer) GetConfig(context.Context, *GetConfigRequest) (*GetConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetConfig not implemented")
}
func (UnimplementedL4BalancerApiServer) UpdateConfig(context.Context, *UpdateConfigRequest) (*UpdateConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateConfig not implemented")
}
func (UnimplementedL4BalancerApiServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedL4BalancerApiServer) ListBackends(context.Context, *ListBackendsRequest) (*ListBackendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBackends not implemented")
}
func (UnimplementedL4BalancerApiServer) SetBackendStatus(context.Context, *SetBackendStatusRequest) (*SetBackendStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetBackendStatus not implemented")
}
func (UnimplementedL4BalancerApiServer) Ping(context.Context, *EmptyMessage) (*EmptyMessage, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedL4BalancerApiServer) mustEmbedUnimplementedL4BalancerApiServer() {}
func (UnimplementedL4BalancerApiServer) testEmbeddedByValue()                       {}

// UnsafeL4BalancerApiServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to L4BalancerApiServer will
// result in compilation errors.
type UnsafeL4BalancerApiServer interface {
	mustEmbedUnimplementedL4BalancerApiServer()
}

func RegisterL4BalancerApiServer(s grpc.ServiceRegistrar, srv L4BalancerApiServer) {
	// If the following call panics, it indicates UnimplementedL4BalancerApiServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&L4BalancerApi_ServiceDesc, srv)
}

func _L4BalancerApi_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L4BalancerApiServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L4BalancerApi_GetConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L4BalancerApiServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L4BalancerApi_UpdateConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L4BalancerApiServer).UpdateConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L4BalancerApi_UpdateConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L4BalancerApiServer).UpdateConfig(ctx, req.(*UpdateConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L4BalancerApi_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L4BalancerApiServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L4BalancerApi_ListServices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L4BalancerApiServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L4BalancerApi_ListBackends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBackendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L4BalancerApiServer).ListBackends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L4BalancerApi_ListBackends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L4BalancerApiServer).ListBackends(ctx, req.(*ListBackendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L4BalancerApi_SetBackendStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBackendStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L4BalancerApiServer).SetBackendStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L4BalancerApi_SetBackendStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L4BalancerApiServer).SetBackendStatus(ctx, req.(*SetBackendStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _L4BalancerApi_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(L4BalancerApiServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: L4BalancerApi_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(L4BalancerApiServer).Ping(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// L4BalancerApi_ServiceDesc is the grpc.ServiceDesc for L4BalancerApi service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var L4BalancerApi_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.L4BalancerApi",
	HandlerType: (*L4BalancerApiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetConfig",
			Handler:    _L4BalancerApi_GetConfig_Handler,
		},
		{
			MethodName: "UpdateConfig",
			Handler:    _L4BalancerApi_UpdateConfig_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _L4BalancerApi_ListServices_Handler,
		},
		{
			MethodName: "ListBackends",
			Handler:    _L4BalancerApi_ListBackends_Handler,
		},
		{
			MethodName: "SetBackendStatus",
			Handler:    _L4BalancerApi_SetBackendStatus_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _L4BalancerApi_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/controlplane-api.proto",
}
